/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoseRouteImport } from './routes/pose'
import { Route as HenshinRouteImport } from './routes/henshin'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as IndexRouteImport } from './routes/index'

const PoseRoute = PoseRouteImport.update({
  id: '/pose',
  path: '/pose',
  getParentRoute: () => rootRouteImport,
} as any)
const HenshinRoute = HenshinRouteImport.update({
  id: '/henshin',
  path: '/henshin',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detect': typeof DetectRoute
  '/henshin': typeof HenshinRoute
  '/pose': typeof PoseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detect': typeof DetectRoute
  '/henshin': typeof HenshinRoute
  '/pose': typeof PoseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detect': typeof DetectRoute
  '/henshin': typeof HenshinRoute
  '/pose': typeof PoseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/detect' | '/henshin' | '/pose'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/detect' | '/henshin' | '/pose'
  id: '__root__' | '/' | '/detect' | '/henshin' | '/pose'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetectRoute: typeof DetectRoute
  HenshinRoute: typeof HenshinRoute
  PoseRoute: typeof PoseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pose': {
      id: '/pose'
      path: '/pose'
      fullPath: '/pose'
      preLoaderRoute: typeof PoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/henshin': {
      id: '/henshin'
      path: '/henshin'
      fullPath: '/henshin'
      preLoaderRoute: typeof HenshinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetectRoute: DetectRoute,
  HenshinRoute: HenshinRoute,
  PoseRoute: PoseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
