/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRouteImport } from './routes/select'
import { Route as ResultRouteImport } from './routes/result'
import { Route as PairingTestRouteImport } from './routes/pairing-test'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as NfcTestRouteImport } from './routes/nfc-test'
import { Route as ModelCheckRouteImport } from './routes/model-check'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as BattleTestRouteImport } from './routes/battle-test'
import { Route as BattleRouteImport } from './routes/battle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'

const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingTestRoute = PairingTestRouteImport.update({
  id: '/pairing-test',
  path: '/pairing-test',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcTestRoute = NfcTestRouteImport.update({
  id: '/nfc-test',
  path: '/nfc-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelCheckRoute = ModelCheckRouteImport.update({
  id: '/model-check',
  path: '/model-check',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleTestRoute = BattleTestRouteImport.update({
  id: '/battle-test',
  path: '/battle-test',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleRoute = BattleRouteImport.update({
  id: '/battle',
  path: '/battle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/battle-test': typeof BattleTestRoute
  '/detect': typeof DetectRoute
  '/model-check': typeof ModelCheckRoute
  '/nfc-test': typeof NfcTestRoute
  '/pairing': typeof PairingRoute
  '/pairing-test': typeof PairingTestRoute
  '/result': typeof ResultRoute
  '/select': typeof SelectRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/battle-test': typeof BattleTestRoute
  '/detect': typeof DetectRoute
  '/model-check': typeof ModelCheckRoute
  '/nfc-test': typeof NfcTestRoute
  '/pairing': typeof PairingRoute
  '/pairing-test': typeof PairingTestRoute
  '/result': typeof ResultRoute
  '/select': typeof SelectRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/battle': typeof BattleRoute
  '/battle-test': typeof BattleTestRoute
  '/detect': typeof DetectRoute
  '/model-check': typeof ModelCheckRoute
  '/nfc-test': typeof NfcTestRoute
  '/pairing': typeof PairingRoute
  '/pairing-test': typeof PairingTestRoute
  '/result': typeof ResultRoute
  '/select': typeof SelectRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/battle'
    | '/battle-test'
    | '/detect'
    | '/model-check'
    | '/nfc-test'
    | '/pairing'
    | '/pairing-test'
    | '/result'
    | '/select'
    | '/auth/register'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/battle'
    | '/battle-test'
    | '/detect'
    | '/model-check'
    | '/nfc-test'
    | '/pairing'
    | '/pairing-test'
    | '/result'
    | '/select'
    | '/auth/register'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/battle'
    | '/battle-test'
    | '/detect'
    | '/model-check'
    | '/nfc-test'
    | '/pairing'
    | '/pairing-test'
    | '/result'
    | '/select'
    | '/auth/register'
    | '/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BattleRoute: typeof BattleRoute
  BattleTestRoute: typeof BattleTestRoute
  DetectRoute: typeof DetectRoute
  ModelCheckRoute: typeof ModelCheckRoute
  NfcTestRoute: typeof NfcTestRoute
  PairingRoute: typeof PairingRoute
  PairingTestRoute: typeof PairingTestRoute
  ResultRoute: typeof ResultRoute
  SelectRoute: typeof SelectRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing-test': {
      id: '/pairing-test'
      path: '/pairing-test'
      fullPath: '/pairing-test'
      preLoaderRoute: typeof PairingTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc-test': {
      id: '/nfc-test'
      path: '/nfc-test'
      fullPath: '/nfc-test'
      preLoaderRoute: typeof NfcTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-check': {
      id: '/model-check'
      path: '/model-check'
      fullPath: '/model-check'
      preLoaderRoute: typeof ModelCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle-test': {
      id: '/battle-test'
      path: '/battle-test'
      fullPath: '/battle-test'
      preLoaderRoute: typeof BattleTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle': {
      id: '/battle'
      path: '/battle'
      fullPath: '/battle'
      preLoaderRoute: typeof BattleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BattleRoute: BattleRoute,
  BattleTestRoute: BattleTestRoute,
  DetectRoute: DetectRoute,
  ModelCheckRoute: ModelCheckRoute,
  NfcTestRoute: NfcTestRoute,
  PairingRoute: PairingRoute,
  PairingTestRoute: PairingTestRoute,
  ResultRoute: ResultRoute,
  SelectRoute: SelectRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
